#!/usr/bin/env python3
"""Analyze bucket statistics from `training_epochs.csv`.

The input CSV is expected to be generated by `script/parse_alpha_training_logs.py`.
It summarizes per-bucket accuracy, true bucket rate, predicted min-bucket rate,
and derived epoch-level metrics.

Outputs:
- `group_summary.csv`
- `bucket_summary.csv`
- `epoch_overview.csv`
- optional plots per source file
"""

from __future__ import annotations

import argparse
import csv
import math
import re
import statistics
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any


BUCKET_FIELD_RE = re.compile(r"^(?P<prefix>per_bucket|true_bucket_rate|pred_min_bucket_rate)_(?P<bucket>\d+)_mean$")


def parse_float(value: Any) -> float | None:
    if value is None:
        return None
    text = str(value).strip()
    if not text or text.lower() in {"nan", "none", "null"}:
        return None
    try:
        number = float(text)
    except ValueError:
        return None
    return number if math.isfinite(number) else None


def parse_int(value: Any) -> int | None:
    number = parse_float(value)
    if number is None:
        return None
    return int(number)


def fmean(values: list[float]) -> float | None:
    return statistics.fmean(values) if values else None


def pstdev(values: list[float]) -> float | None:
    if not values:
        return None
    return statistics.pstdev(values) if len(values) > 1 else 0.0


def linear_slope(points: list[tuple[float, float]]) -> float | None:
    if len(points) < 2:
        return None
    xs = [p[0] for p in points]
    ys = [p[1] for p in points]
    x_mean = statistics.fmean(xs)
    y_mean = statistics.fmean(ys)
    denom = sum((x - x_mean) ** 2 for x in xs)
    if denom == 0:
        return None
    numer = sum((x - x_mean) * (y - y_mean) for x, y in points)
    return numer / denom


def safe_name(text: str) -> str:
    return "".join(ch if ch.isalnum() or ch in {"-", "_"} else "_" for ch in text)


def load_csv(csv_path: Path) -> tuple[list[dict[str, Any]], list[str]]:
    with csv_path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        rows = [row for row in reader if any((v or "").strip() for v in row.values())]
        if reader.fieldnames is None:
            raise SystemExit(f"CSV has no header: {csv_path}")
        return rows, reader.fieldnames


def discover_bucket_ids(fieldnames: list[str]) -> list[int]:
    bucket_ids: set[int] = set()
    for field in fieldnames:
        match = BUCKET_FIELD_RE.match(field)
        if match:
            bucket_ids.add(int(match.group("bucket")))
    return sorted(bucket_ids)


def group_rows(rows: list[dict[str, Any]], group_by: str) -> dict[str, list[dict[str, Any]]]:
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in rows:
        key = row.get(group_by, "") if group_by != "all" else "ALL"
        key = (key or "UNKNOWN").strip()
        grouped[key].append(row)
    return dict(grouped)


def get_metric(row: dict[str, Any], key: str) -> float | None:
    return parse_float(row.get(key))


def bucket_metric(row: dict[str, Any], prefix: str, bucket_id: int) -> float | None:
    return get_metric(row, f"{prefix}_{bucket_id}_mean")


def mean_epoch_metrics(rows: list[dict[str, Any]], bucket_ids: list[int]) -> list[dict[str, Any]]:
    metrics: list[dict[str, Any]] = []
    for row in rows:
        epoch = parse_int(row.get("epoch"))
        if epoch is None:
            continue

        accs = [bucket_metric(row, "per_bucket", bucket_id) for bucket_id in bucket_ids]
        true_rates = [bucket_metric(row, "true_bucket_rate", bucket_id) for bucket_id in bucket_ids]
        pred_rates = [bucket_metric(row, "pred_min_bucket_rate", bucket_id) for bucket_id in bucket_ids]

        acc_pairs = [(i, v) for i, v in enumerate(accs) if v is not None]
        true_pairs = [(i, v) for i, v in enumerate(true_rates) if v is not None]
        pred_pairs = [(i, v) for i, v in enumerate(pred_rates) if v is not None]

        macro_acc = fmean([v for _, v in acc_pairs])
        weighted_acc = None
        if acc_pairs and true_pairs and len(acc_pairs) == len(true_pairs):
            weighted_acc = sum(accs[i] * true_rates[i] for i in range(len(bucket_ids)) if accs[i] is not None and true_rates[i] is not None)
        alignment_l1 = None
        if true_pairs and pred_pairs and len(true_pairs) == len(pred_pairs):
            alignment_l1 = sum(abs(pred_rates[i] - true_rates[i]) for i in range(len(bucket_ids)) if pred_rates[i] is not None and true_rates[i] is not None)

        metrics.append(
            {
                "epoch": epoch,
                "reward_mean": get_metric(row, "reward_mean"),
                "macro_bucket_acc": macro_acc,
                "weighted_bucket_acc": weighted_acc,
                "alignment_l1": alignment_l1,
                "min_alpha_bucket_acc": get_metric(row, "min_alpha_bucket_acc_mean"),
                "strict_min_alpha_bucket_acc": get_metric(row, "strict_min_alpha_bucket_acc_mean"),
                "target_in_topk_rate": get_metric(row, "target_in_topk_rate_mean"),
                "alpha_gap_mean": get_metric(row, "alpha_gap_mean"),
                "top_true_bucket": max(true_pairs, key=lambda item: item[1])[0] if true_pairs else None,
                "top_pred_bucket": max(pred_pairs, key=lambda item: item[1])[0] if pred_pairs else None,
                "top_acc_bucket": max(acc_pairs, key=lambda item: item[1])[0] if acc_pairs else None,
            }
        )
    return metrics


def summarize_epoch_metrics(epoch_metrics: list[dict[str, Any]]) -> dict[str, Any]:
    def values(name: str) -> list[float]:
        return [float(row[name]) for row in epoch_metrics if row.get(name) is not None]

    reward_values = values("reward_mean")
    macro_values = values("macro_bucket_acc")
    weighted_values = values("weighted_bucket_acc")
    align_values = values("alignment_l1")
    min_acc_values = values("min_alpha_bucket_acc")
    strict_min_acc_values = values("strict_min_alpha_bucket_acc")
    topk_values = values("target_in_topk_rate")
    gap_values = values("alpha_gap_mean")

    summary: dict[str, Any] = {
        "epochs": len(epoch_metrics),
        "reward_mean": fmean(reward_values),
        "reward_std": pstdev(reward_values),
        "macro_bucket_acc_mean": fmean(macro_values),
        "macro_bucket_acc_std": pstdev(macro_values),
        "weighted_bucket_acc_mean": fmean(weighted_values),
        "weighted_bucket_acc_std": pstdev(weighted_values),
        "alignment_l1_mean": fmean(align_values),
        "alignment_l1_std": pstdev(align_values),
        "min_alpha_bucket_acc_mean": fmean(min_acc_values),
        "strict_min_alpha_bucket_acc_mean": fmean(strict_min_acc_values),
        "target_in_topk_rate_mean": fmean(topk_values),
        "alpha_gap_mean": fmean(gap_values),
    }

    if reward_values:
        reward_best = max(epoch_metrics, key=lambda row: row.get("reward_mean") if row.get("reward_mean") is not None else -float("inf"))
        summary["best_reward"] = reward_best.get("reward_mean")
        summary["best_reward_epoch"] = reward_best.get("epoch")
    if macro_values:
        macro_best = max(epoch_metrics, key=lambda row: row.get("macro_bucket_acc") if row.get("macro_bucket_acc") is not None else -float("inf"))
        summary["best_macro_bucket_acc"] = macro_best.get("macro_bucket_acc")
        summary["best_macro_bucket_acc_epoch"] = macro_best.get("epoch")
    if align_values:
        align_best = min(epoch_metrics, key=lambda row: row.get("alignment_l1") if row.get("alignment_l1") is not None else float("inf"))
        summary["best_alignment_l1"] = align_best.get("alignment_l1")
        summary["best_alignment_epoch"] = align_best.get("epoch")

    if epoch_metrics:
        final = epoch_metrics[-1]
        summary["final_epoch"] = final.get("epoch")
        summary["final_reward"] = final.get("reward_mean")
        summary["final_macro_bucket_acc"] = final.get("macro_bucket_acc")
        summary["final_weighted_bucket_acc"] = final.get("weighted_bucket_acc")
        summary["final_alignment_l1"] = final.get("alignment_l1")
        summary["final_min_alpha_bucket_acc"] = final.get("min_alpha_bucket_acc")
        summary["final_strict_min_alpha_bucket_acc"] = final.get("strict_min_alpha_bucket_acc")
        summary["final_target_in_topk_rate"] = final.get("target_in_topk_rate")
        summary["final_alpha_gap_mean"] = final.get("alpha_gap_mean")
        summary["final_top_true_bucket"] = final.get("top_true_bucket")
        summary["final_top_pred_bucket"] = final.get("top_pred_bucket")
        summary["final_top_acc_bucket"] = final.get("top_acc_bucket")

    top_true_counts = Counter(row["top_true_bucket"] for row in epoch_metrics if row.get("top_true_bucket") is not None)
    top_pred_counts = Counter(row["top_pred_bucket"] for row in epoch_metrics if row.get("top_pred_bucket") is not None)
    top_acc_counts = Counter(row["top_acc_bucket"] for row in epoch_metrics if row.get("top_acc_bucket") is not None)
    summary["mode_top_true_bucket"] = top_true_counts.most_common(1)[0][0] if top_true_counts else None
    summary["mode_top_pred_bucket"] = top_pred_counts.most_common(1)[0][0] if top_pred_counts else None
    summary["mode_top_acc_bucket"] = top_acc_counts.most_common(1)[0][0] if top_acc_counts else None
    return summary


def summarize_buckets(rows: list[dict[str, Any]], bucket_ids: list[int], group_key: str) -> list[dict[str, Any]]:
    bucket_rows: list[dict[str, Any]] = []
    epochs = [parse_int(row.get("epoch")) for row in rows]
    valid_epochs = [epoch for epoch in epochs if epoch is not None]
    if not valid_epochs:
        return bucket_rows

    for bucket_id in bucket_ids:
        acc_values: list[float] = []
        acc_std_values: list[float] = []
        true_values: list[float] = []
        true_std_values: list[float] = []
        pred_values: list[float] = []
        pred_std_values: list[float] = []
        gap_values: list[float] = []
        abs_gap_values: list[float] = []
        acc_points: list[tuple[float, float]] = []
        true_points: list[tuple[float, float]] = []
        pred_points: list[tuple[float, float]] = []
        gap_points: list[tuple[float, float]] = []
        acc_by_epoch: list[tuple[int, float]] = []

        for row in rows:
            epoch = parse_int(row.get("epoch"))
            if epoch is None:
                continue

            acc = bucket_metric(row, "per_bucket", bucket_id)
            acc_std = get_metric(row, f"per_bucket_{bucket_id}_std")
            true_rate = bucket_metric(row, "true_bucket_rate", bucket_id)
            true_std = get_metric(row, f"true_bucket_rate_{bucket_id}_std")
            pred_rate = bucket_metric(row, "pred_min_bucket_rate", bucket_id)
            pred_std = get_metric(row, f"pred_min_bucket_rate_{bucket_id}_std")

            if acc is not None:
                acc_values.append(acc)
                acc_by_epoch.append((epoch, acc))
                acc_points.append((float(epoch), float(acc)))
            if acc_std is not None:
                acc_std_values.append(acc_std)
            if true_rate is not None:
                true_values.append(true_rate)
                true_points.append((float(epoch), float(true_rate)))
            if true_std is not None:
                true_std_values.append(true_std)
            if pred_rate is not None:
                pred_values.append(pred_rate)
                pred_points.append((float(epoch), float(pred_rate)))
            if pred_std is not None:
                pred_std_values.append(pred_std)
            if true_rate is not None and pred_rate is not None:
                gap = pred_rate - true_rate
                gap_values.append(gap)
                abs_gap_values.append(abs(gap))
                gap_points.append((float(epoch), float(gap)))

        def best_epoch_value(items: list[tuple[int, float]], maximize: bool = True) -> tuple[int | None, float | None]:
            if not items:
                return None, None
            return max(items, key=lambda item: item[1]) if maximize else min(items, key=lambda item: item[1])

        acc_best_epoch, acc_best = best_epoch_value(acc_by_epoch, maximize=True)

        bucket_rows.append(
            {
                "group_key": group_key,
                "bucket_id": bucket_id,
                "epochs": len(valid_epochs),
                "acc_mean": fmean(acc_values),
                "acc_std": pstdev(acc_values),
                "acc_min": min(acc_values) if acc_values else None,
                "acc_max": max(acc_values) if acc_values else None,
                "acc_last": acc_values[-1] if acc_values else None,
                "acc_best": acc_best,
                "acc_best_epoch": acc_best_epoch,
                "acc_within_epoch_std_mean": fmean(acc_std_values),
                "acc_trend_slope": linear_slope(acc_points),
                "true_rate_mean": fmean(true_values),
                "true_rate_std": pstdev(true_values),
                "true_rate_min": min(true_values) if true_values else None,
                "true_rate_max": max(true_values) if true_values else None,
                "true_rate_last": true_values[-1] if true_values else None,
                "true_rate_within_epoch_std_mean": fmean(true_std_values),
                "true_rate_trend_slope": linear_slope(true_points),
                "pred_rate_mean": fmean(pred_values),
                "pred_rate_std": pstdev(pred_values),
                "pred_rate_min": min(pred_values) if pred_values else None,
                "pred_rate_max": max(pred_values) if pred_values else None,
                "pred_rate_last": pred_values[-1] if pred_values else None,
                "pred_rate_within_epoch_std_mean": fmean(pred_std_values),
                "pred_rate_trend_slope": linear_slope(pred_points),
                "gap_mean": fmean(gap_values),
                "gap_abs_mean": fmean(abs_gap_values),
                "gap_last": gap_values[-1] if gap_values else None,
                "gap_trend_slope": linear_slope(gap_points),
            }
        )

    return bucket_rows


def write_csv(path: Path, rows: list[dict[str, Any]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row.get(field) for field in fieldnames})


def plot_group(report_dir: Path, group_key: str, bucket_rows: list[dict[str, Any]], epoch_rows: list[dict[str, Any]]) -> str | None:
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except Exception:
        return None

    if not bucket_rows or not epoch_rows:
        return None

    bucket_rows = sorted(bucket_rows, key=lambda row: row["bucket_id"])
    epoch_rows = sorted(epoch_rows, key=lambda row: row["epoch"])
    buckets = [int(row["bucket_id"]) for row in bucket_rows]

    acc_means = [row.get("acc_mean") for row in bucket_rows]
    true_means = [row.get("true_rate_mean") for row in bucket_rows]
    pred_means = [row.get("pred_rate_mean") for row in bucket_rows]
    gap_means = [row.get("gap_mean") for row in bucket_rows]

    epochs = [row["epoch"] for row in epoch_rows]
    macro = [row.get("macro_bucket_acc") for row in epoch_rows]
    alignment = [row.get("alignment_l1") for row in epoch_rows]
    reward = [row.get("reward_mean") for row in epoch_rows]

    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    fig.suptitle(f"Bucket analysis - {group_key}", fontsize=14, fontweight="bold")

    ax = axes[0, 0]
    ax.bar(buckets, acc_means, color="#4C78A8")
    ax.set_title("Per-bucket accuracy mean")
    ax.set_xlabel("Bucket")
    ax.set_ylabel("Accuracy")
    ax.set_ylim(0, max([v for v in acc_means if v is not None] + [1.0]) * 1.15)
    ax.grid(axis="y", alpha=0.25)

    ax = axes[0, 1]
    ax.plot(buckets, true_means, marker="o", label="True rate", color="#59A14F")
    ax.plot(buckets, pred_means, marker="o", label="Pred min rate", color="#F28E2B")
    ax.set_title("Bucket rate distribution")
    ax.set_xlabel("Bucket")
    ax.set_ylabel("Rate")
    ax.grid(axis="y", alpha=0.25)
    ax.legend()

    ax = axes[1, 0]
    ax.bar(buckets, gap_means, color="#E15759")
    ax.axhline(0.0, color="black", linewidth=1)
    ax.set_title("Predicted minus true rate")
    ax.set_xlabel("Bucket")
    ax.set_ylabel("Gap")
    ax.grid(axis="y", alpha=0.25)

    ax = axes[1, 1]
    ax.plot(epochs, macro, label="Macro acc", color="#4C78A8")
    ax.plot(epochs, alignment, label="Alignment L1", color="#E15759")
    ax2 = ax.twinx()
    ax2.plot(epochs, reward, label="Reward", color="#59A14F", alpha=0.6)
    ax.set_title("Epoch trends")
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Bucket metrics")
    ax2.set_ylabel("Reward")
    ax.grid(alpha=0.25)

    lines1, labels1 = ax.get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()
    ax.legend(lines1 + lines2, labels1 + labels2, loc="best")

    fig.tight_layout()
    out_path = report_dir / f"bucket_overview_{safe_name(group_key)}.png"
    fig.savefig(out_path, dpi=160, bbox_inches="tight")
    plt.close(fig)
    return out_path.name


def main() -> None:
    parser = argparse.ArgumentParser(description="Analyze bucket statistics from training_epochs.csv")
    parser.add_argument(
        "--csv",
        default="analysis/alpha_training_reports/training_epochs.csv",
        help="Input CSV generated from the training logs",
    )
    parser.add_argument(
        "--output-dir",
        default="analysis/alpha_training_reports/bucket_analysis",
        help="Directory for analysis outputs",
    )
    parser.add_argument(
        "--group-by",
        default="source_file",
        choices=["source_file", "job_id", "all"],
        help="How to group rows before analyzing buckets",
    )
    parser.add_argument(
        "--no-plot",
        action="store_true",
        help="Skip PNG plots",
    )
    args = parser.parse_args()

    csv_path = Path(args.csv)
    rows, fieldnames = load_csv(csv_path)
    bucket_ids = discover_bucket_ids(fieldnames)
    if not bucket_ids:
        raise SystemExit("No bucket columns found in the CSV.")

    grouped = group_rows(rows, args.group_by)
    report_dir = Path(args.output_dir)
    report_dir.mkdir(parents=True, exist_ok=True)

    all_group_summaries: list[dict[str, Any]] = []
    all_bucket_rows: list[dict[str, Any]] = []
    all_epoch_rows: list[dict[str, Any]] = []
    plot_files: list[str] = []

    for group_key, group_rows_list in sorted(grouped.items(), key=lambda item: item[0]):
        group_rows_list = sorted(group_rows_list, key=lambda row: parse_int(row.get("epoch")) or 0)
        epoch_rows = mean_epoch_metrics(group_rows_list, bucket_ids)
        bucket_rows = summarize_buckets(group_rows_list, bucket_ids, group_key)
        summary = summarize_epoch_metrics(epoch_rows)
        summary["group_key"] = group_key

        if bucket_rows:
            bucket_by_id = {row["bucket_id"]: row for row in bucket_rows}
            top_acc_bucket = max(bucket_rows, key=lambda row: row.get("acc_mean") if row.get("acc_mean") is not None else -float("inf"))
            top_true_bucket = max(bucket_rows, key=lambda row: row.get("true_rate_mean") if row.get("true_rate_mean") is not None else -float("inf"))
            top_pred_bucket = max(bucket_rows, key=lambda row: row.get("pred_rate_mean") if row.get("pred_rate_mean") is not None else -float("inf"))
            summary["top_acc_bucket_mean"] = top_acc_bucket["bucket_id"]
            summary["top_true_bucket_mean"] = top_true_bucket["bucket_id"]
            summary["top_pred_bucket_mean"] = top_pred_bucket["bucket_id"]
            summary["top_acc_bucket_mean_value"] = top_acc_bucket.get("acc_mean")
            summary["top_true_bucket_mean_value"] = top_true_bucket.get("true_rate_mean")
            summary["top_pred_bucket_mean_value"] = top_pred_bucket.get("pred_rate_mean")
            summary["macro_bucket_acc_over_buckets"] = fmean([row.get("acc_mean") for row in bucket_rows if row.get("acc_mean") is not None])
            summary["true_rate_l1_gap_over_buckets"] = sum(
                abs((bucket_by_id[b].get("pred_rate_mean") or 0.0) - (bucket_by_id[b].get("true_rate_mean") or 0.0))
                for b in bucket_ids
                if bucket_by_id[b].get("pred_rate_mean") is not None and bucket_by_id[b].get("true_rate_mean") is not None
            )

        all_group_summaries.append(summary)
        all_bucket_rows.extend(bucket_rows)
        all_epoch_rows.extend({"group_key": group_key, **row} for row in epoch_rows)

        if not args.no_plot:
            plotted = plot_group(report_dir, group_key, bucket_rows, epoch_rows)
            if plotted:
                plot_files.append(plotted)

        print(f"[{group_key}] epochs={summary.get('epochs')} reward={summary.get('reward_mean')} macro_acc={summary.get('macro_bucket_acc_mean')} align_l1={summary.get('alignment_l1_mean')}")
        print(
            f"  top buckets: acc={summary.get('top_acc_bucket_mean')} "
            f"true={summary.get('top_true_bucket_mean')} pred={summary.get('top_pred_bucket_mean')}"
        )

    group_fields = [
        "group_key",
        "epochs",
        "reward_mean",
        "reward_std",
        "macro_bucket_acc_mean",
        "macro_bucket_acc_std",
        "weighted_bucket_acc_mean",
        "weighted_bucket_acc_std",
        "alignment_l1_mean",
        "alignment_l1_std",
        "min_alpha_bucket_acc_mean",
        "strict_min_alpha_bucket_acc_mean",
        "target_in_topk_rate_mean",
        "alpha_gap_mean",
        "best_reward",
        "best_reward_epoch",
        "best_macro_bucket_acc",
        "best_macro_bucket_acc_epoch",
        "best_alignment_l1",
        "best_alignment_epoch",
        "final_epoch",
        "final_reward",
        "final_macro_bucket_acc",
        "final_weighted_bucket_acc",
        "final_alignment_l1",
        "final_min_alpha_bucket_acc",
        "final_strict_min_alpha_bucket_acc",
        "final_target_in_topk_rate",
        "final_alpha_gap_mean",
        "final_top_true_bucket",
        "final_top_pred_bucket",
        "final_top_acc_bucket",
        "mode_top_true_bucket",
        "mode_top_pred_bucket",
        "mode_top_acc_bucket",
        "top_acc_bucket_mean",
        "top_true_bucket_mean",
        "top_pred_bucket_mean",
        "top_acc_bucket_mean_value",
        "top_true_bucket_mean_value",
        "top_pred_bucket_mean_value",
        "macro_bucket_acc_over_buckets",
        "true_rate_l1_gap_over_buckets",
    ]

    bucket_fields = [
        "group_key",
        "bucket_id",
        "epochs",
        "acc_mean",
        "acc_std",
        "acc_min",
        "acc_max",
        "acc_last",
        "acc_best",
        "acc_best_epoch",
        "acc_within_epoch_std_mean",
        "acc_trend_slope",
        "true_rate_mean",
        "true_rate_std",
        "true_rate_min",
        "true_rate_max",
        "true_rate_last",
        "true_rate_within_epoch_std_mean",
        "true_rate_trend_slope",
        "pred_rate_mean",
        "pred_rate_std",
        "pred_rate_min",
        "pred_rate_max",
        "pred_rate_last",
        "pred_rate_within_epoch_std_mean",
        "pred_rate_trend_slope",
        "gap_mean",
        "gap_abs_mean",
        "gap_last",
        "gap_trend_slope",
    ]

    epoch_fields = [
        "group_key",
        "epoch",
        "reward_mean",
        "macro_bucket_acc",
        "weighted_bucket_acc",
        "alignment_l1",
        "min_alpha_bucket_acc",
        "strict_min_alpha_bucket_acc",
        "target_in_topk_rate",
        "alpha_gap_mean",
        "top_true_bucket",
        "top_pred_bucket",
        "top_acc_bucket",
    ]

    write_csv(report_dir / "group_summary.csv", all_group_summaries, group_fields)
    write_csv(report_dir / "bucket_summary.csv", all_bucket_rows, bucket_fields)
    write_csv(report_dir / "epoch_overview.csv", all_epoch_rows, epoch_fields)

    print(f"Wrote: {report_dir / 'group_summary.csv'}")
    print(f"Wrote: {report_dir / 'bucket_summary.csv'}")
    print(f"Wrote: {report_dir / 'epoch_overview.csv'}")
    for name in plot_files:
        print(f"Wrote: {report_dir / name}")


if __name__ == "__main__":
    main()
